name: Android CI

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (33.0.0) -- optional
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Rename file 
      run: mv ${{steps.sign_app.outputs.signedReleaseFile}} ${{github.ref_name}}_signed.apk

    - uses: actions/upload-artifact@v4
      with:
        name: signed release
        path: ${{github.ref_name}}_signed.apk

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ${{github.ref_name}}_signed.apk
        body: "release"
