name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build database file
      run: ./gradlew Build_PointsCacheDB_TFL
    - name: Build with Gradle
      run: ./gradlew build
    - name: Remove database file
      run: ./gradlew Remove_PointsCacheDB_TFL
